<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN-NFDCINOH1RK" ignored="0" name="Group2" tests="2" failures="2" timestamp="2020-06-17T07:18:51 UTC" time="14.8" errors="0">
  <testcase name="ReadWrite" time="9.403" classname="POM.excelloop">
    <failure type="java.io.FileNotFoundException" message="C:\Bhavya\ddt_demo.xlsx (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: C:\Bhavya\ddt_demo.xlsx (The process cannot access the file because it is being used by another process)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(Unknown Source)
at java.io.FileOutputStream.<init>(Unknown Source)
at java.io.FileOutputStream.<init>(Unknown Source)
at POM.excelloop.ReadWrite(excelloop.java:91)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- ReadWrite -->
  <testcase name="ValidLogin__fact" time="1.443" classname="POM.VerifyLogin_PgFactory">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at POM.VerifyLogin_PgFactory.ValidLogin__fact(VerifyLogin_PgFactory.java:43)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- ValidLogin__fact -->
</testsuite> <!-- Group2 -->
